# -*- coding: utf-8 -*-
"""Pandas_Profling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q015LclXpg7PauNRo2-BQ9faC8M173IA
"""

#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_excel(r'/content/Athulya_Bike_Buyers_Dataset_Project_.xlsx') # loading the training data

train.head()

train.tail() # looking at the training data from end

train.describe()

# Install ydata-profiling instead of pandas-profiling
!pip install ydata-profiling

# Install compatible versions of numba and visions
!pip install numba==0.58.1 visions==0.7.6

# Import ProfileReport from ydata_profiling
from ydata_profiling import ProfileReport

if not train.empty:
  profile = ProfileReport(train, title="Pandas Profiling Report")
  profile.to_widgets()